### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [willbsp/habits#14]
Thanks a lot for making your app available under a FOSS license! It's a pity non-developers will need an account with a walled garden to use it, as the APK is only available via Google Play. Would you consider attaching APKs to their corresponding [Releases](https://github.com/willbsp/habits/releases), so people without a Google account (and maybe even with de-googled devices) can access it? Or maybe even bring your app to [F-Droid](https://f-droid.org/)? Thanks in advance!

**Comment by willbsp** [comment]
Hi, thanks for your interest in my project! An APK for release 1.0 is now available for download from the releases page [here](https://github.com/willbsp/habits/releases/tag/v1.0.0).
As for bringing the app to F-Droid, I have just created a separate [issue](https://github.com/willbsp/habits/issues/15) for that.

**Comment by IzzySoft** [comment]
That was fast – thanks a lot! Habits will become [available in my repo](https://apt.izzysoft.de/packages/com.willbsp.habits/) with the next sync around 6 pm UTC then, to make it even easier for said people to discover it and keep the app updated automatically using the [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181) of their choice. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you wish! New releases will be fetched automatically within 24h from your attaching an APK to a new release tag here.

Short note: `versionName` of the APK (`1.0`) does not fully match the tag name `v1.0.0` (the leading `v` is fine, it's just the "patch" from your [semver](https://semver.org/) that's missing in the `versionName`). So while on it, let me state something obvious: please remember to increase `versionCode` with each new release as well :wink:
