### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by willbsp** [willbsp/habits#15]
Bring Habits to F-Droid.

**Comment by IzzySoft** [comment]
Thanks for picking up on bringing your app to [F-Droid.org](https://f-droid.org/). Being one of the maintainers there, I gladly help you with that. Will you accept a PR to establish [Fastlane structures](https://gitlab.com/-/snippets/1895688) in your repo here? I can offer you what I've set up for my repo, and you can then adjust that to your liking. F-Droid will need that to present your app.

**Comment by willbsp** [comment]
Sounds great! Submit the PR and I will have a look at it.

**Comment by IzzySoft** [comment]
There you go :smiley: I've summed up some core points there for easy reference, so if needed you can easily find them.

**Comment by willbsp** [comment]
@IzzySoft Thank you for your help with establishing fastlane structures. Is there anything else you would recommend doing before opening a request for packaging on F-Droid?

**Comment by IzzySoft** [comment]
I'd say you're set now. More details might come up once issuebot presents its report, but that we can deal with when it happens. So feel encouraged to go ahead!
