### ISSUE TITLE
Pressing on checkmark causes animation flicker

### ISSUE THREAD

**Issue by HeadPlug** [willbsp/habits#22]
Pressing a checkmark on a habit makes it flicker; I'm assuming this is a bug as it's different from the  GIF in the readme:

https://github.com/willbsp/habits/assets/57101103/994af02a-5251-41cf-8fec-bfce250b50c5

https://github.com/willbsp/habits/raw/dev/screenshots/screenshot-1.gif

The animation that happens looks like the one used in the calendar view in the other GIF in the readme:
https://github.com/willbsp/habits/raw/dev/screenshots/screenshot-3.gif

This happens on a Galaxy A52s on Android 13.

Logcat(I hope I did it right): 
[logcat_grepcom.willbsp.habits.txt](https://github.com/willbsp/habits/files/12138263/logcat_grepcom.willbsp.habits.txt)

**Comment by willbsp** [comment]
Hi, the flicker animation is correct. It most likely looks different due to the gif compression on the images in the README. The animation may be something to look at improving in the future. I am closing this issue for now.

**Comment by niktss** [comment]
> Hi, the flicker animation is correct. 

For what it's worth, I'm no longer getting the flicker on 1.2.0, or at least it's a lot smoother now:

https://github.com/willbsp/habits/assets/57101103/b563db7a-12cb-4103-b1b8-116cc396ff28
