### ISSUE TITLE
Habit details button is small and squished to the side

### ISSUE THREAD

**Issue by niktss** [willbsp/habits#23]
The "..." button for getting to the screen with score/streak/edit is smushed to the side, and not very visible on my device:
![Screenshot_20230723_092758_Habits](https://github.com/willbsp/habits/assets/57101103/9d6c3d0a-1c5d-4a1a-948c-5a7c09d69bf9)

The 5 days in view also appear more spread apart than the image in the readme, so I'm assuming this is also a glitch.

This is happening on a Galaxy A52s on Android 13.

**Comment by StoyanDimitrov** [comment]
It may or may not be related but the bottom part of dates are cut too. LG G5 on Android 12.

![habits](https://github.com/willbsp/habits/assets/10962709/bb4db95a-9277-4276-9023-8b3a2e041b5a)

**Comment by willbsp** [comment]
Should be fixed in release [v1.2.0](https://github.com/willbsp/habits/releases/tag/v1.2.0)
